# Generated by Django 5.1.6 on 2025-05-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='images',
        ),
    ]
